"""add_student_profile_fields_to_user

Revision ID: 41d07f72f5b9
Revises: 931e694642d5
Create Date: 2026-09-03 00:07:51.118513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d07f72f5b9'
down_revision: Union[str, Sequence[str], None] = '931e694642d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), server_default='Student', nullable=False))
    op.add_column('users', sa.Column('university', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('degree', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('graduation_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'graduation_year')
    op.drop_column('users', 'degree')
    op.drop_column('users', 'university')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
